// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/product/type/product.proto

package product

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,json=product_id,proto3" json:"productId,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductOrder) Reset() {
	*x = ProductOrder{}
	mi := &file_proto_product_type_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOrder) ProtoMessage() {}

func (x *ProductOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOrder.ProtoReflect.Descriptor instead.
func (*ProductOrder) Descriptor() ([]byte, []int) {
	return file_proto_product_type_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductOrder) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductOrder) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReduceStocksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductOrders []*ProductOrder        `protobuf:"bytes,1,rep,name=productOrders,json=products_order,proto3" json:"productOrders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStocksReq) Reset() {
	*x = ReduceStocksReq{}
	mi := &file_proto_product_type_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStocksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStocksReq) ProtoMessage() {}

func (x *ReduceStocksReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStocksReq.ProtoReflect.Descriptor instead.
func (*ReduceStocksReq) Descriptor() ([]byte, []int) {
	return file_proto_product_type_product_proto_rawDescGZIP(), []int{1}
}

func (x *ReduceStocksReq) GetProductOrders() []*ProductOrder {
	if x != nil {
		return x.ProductOrders
	}
	return nil
}

var File_proto_product_type_product_proto protoreflect.FileDescriptor

const file_proto_product_type_product_proto_rawDesc = "" +
	"\n" +
	" proto/product/type/product.proto\x12\fproduct.type\"I\n" +
	"\fProductOrder\x12\x1d\n" +
	"\tproductId\x18\x01 \x01(\tR\n" +
	"product_id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"T\n" +
	"\x0fReduceStocksReq\x12A\n" +
	"\rproductOrders\x18\x01 \x03(\v2\x1a.product.type.ProductOrderR\x0eproducts_orderB1Z/github.com/revivalxvr/protobuf/protogen/productb\x06proto3"

var (
	file_proto_product_type_product_proto_rawDescOnce sync.Once
	file_proto_product_type_product_proto_rawDescData []byte
)

func file_proto_product_type_product_proto_rawDescGZIP() []byte {
	file_proto_product_type_product_proto_rawDescOnce.Do(func() {
		file_proto_product_type_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_type_product_proto_rawDesc), len(file_proto_product_type_product_proto_rawDesc)))
	})
	return file_proto_product_type_product_proto_rawDescData
}

var file_proto_product_type_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_product_type_product_proto_goTypes = []any{
	(*ProductOrder)(nil),    // 0: product.type.ProductOrder
	(*ReduceStocksReq)(nil), // 1: product.type.ReduceStocksReq
}
var file_proto_product_type_product_proto_depIdxs = []int32{
	0, // 0: product.type.ReduceStocksReq.productOrders:type_name -> product.type.ProductOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_product_type_product_proto_init() }
func file_proto_product_type_product_proto_init() {
	if File_proto_product_type_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_type_product_proto_rawDesc), len(file_proto_product_type_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_product_type_product_proto_goTypes,
		DependencyIndexes: file_proto_product_type_product_proto_depIdxs,
		MessageInfos:      file_proto_product_type_product_proto_msgTypes,
	}.Build()
	File_proto_product_type_product_proto = out.File
	file_proto_product_type_product_proto_goTypes = nil
	file_proto_product_type_product_proto_depIdxs = nil
}
