// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/product/service.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_product_service_proto protoreflect.FileDescriptor

const file_proto_product_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/service.proto\x12\aproduct\x1a\x1bgoogle/protobuf/empty.proto\x1a proto/product/type/product.proto2W\n" +
	"\x0eProductService\x12E\n" +
	"\fReduceStocks\x12\x1d.product.type.ReduceStocksReq\x1a\x16.google.protobuf.EmptyB1Z/github.com/revivalxvr/protobuf/protogen/productb\x06proto3"

var file_proto_product_service_proto_goTypes = []any{
	(*ReduceStocksReq)(nil), // 0: product.type.ReduceStocksReq
	(*emptypb.Empty)(nil),   // 1: google.protobuf.Empty
}
var file_proto_product_service_proto_depIdxs = []int32{
	0, // 0: product.ProductService.ReduceStocks:input_type -> product.type.ReduceStocksReq
	1, // 1: product.ProductService.ReduceStocks:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_product_service_proto_init() }
func file_proto_product_service_proto_init() {
	if File_proto_product_service_proto != nil {
		return
	}
	file_proto_product_type_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_proto_rawDesc), len(file_proto_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_service_proto_depIdxs,
	}.Build()
	File_proto_product_service_proto = out.File
	file_proto_product_service_proto_goTypes = nil
	file_proto_product_service_proto_depIdxs = nil
}
